### ISSUE TITLE
Bark Model error cant generate at all

### ISSUE THREAD

**Issue by vuaieo** [tin2tin/Pallaidium#117]
hi the bark model dont run even here the error messege:

Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.3/scripts/addons/Pallaidium-main/__init__.py", line 3044, in execute
    from resemble_enhance.enhancer.inference import denoise, enhance
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/resemble_enhance/enhancer/inference.py", line 8, in <module>
    from .train import Enhancer, HParams
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/resemble_enhance/enhancer/train.py", line 8, in <module>
    from deepspeed import DeepSpeedConfig
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/__init__.py", line 22, in <module>
    from . import module_inject
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/module_inject/replace_module.py", line 587, in <module>
    from ..pipe import PipelineModule
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 26, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/runtime/config.py", line 41, in <module>
    from ..elasticity import (
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/elasticity/__init__.py", line 10, in <module>
    from .elastic_agent import DSElasticAgent
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/elasticity/elastic_agent.py", line 9, in <module>
    from torch.distributed.elastic.agent.server.api import log, _get_socket_with_port
ImportError: cannot import name 'log' from 'torch.distributed.elastic.agent.server.api' (/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py)
Error: Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/resemble_enhance/enhancer/inference.py", line 8, in <module>
    from .train import Enhancer, HParams
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/resemble_enhance/enhancer/train.py", line 8, in <module>
    from deepspeed import DeepSpeedConfig
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/__init__.py", line 22, in <module>
    from . import module_inject
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/module_inject/replace_module.py", line 587, in <module>
    from ..pipe import PipelineModule
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 26, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/runtime/config.py", line 41, in <module>
    from ..elasticity import (
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/elasticity/__init__.py", line 10, in <module>
    from .elastic_agent import DSElasticAgent
  File "/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/deepspeed/elasticity/elastic_agent.py", line 9, in <module>
    from torch.distributed.elastic.agent.server.api import log, _get_socket_with_port
ImportError: cannot import name 'log' from 'torch.distributed.elastic.agent.server.api' (/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py)

**Comment by tin2tin** [comment]
What I do when I see an error like that, then I google: 
`ImportError: cannot import name 'log' from 'torch.distributed.elastic.agent.server.api'`

And something like this shows up:
https://github.com/huggingface/alignment-handbook/issues/180

![image](https://github.com/user-attachments/assets/b5634e29-fadc-4313-bd93-e0cff59bdfb2)

So, they're suggesting to install a different version of deepspeed: 
`deepspeed==0.14.4`

Now you can try, using the pip add-on, to uninstall deepspeed, and then copy/paste `deepspeed==0.14.4` and install that. Then restart Blender, and see if it is working. 

And then let me know if it is working. And if it is not, I'll disable Bark on Linux, as you know I do not run Pallaidium on Linux, and can't fix bugs not showing up on Windows.

**Comment by tin2tin** [comment]
I've updated Pallaidium som deepspeed==0.14.4 is installed on Linux. So, I'll close this.
