### ISSUE TITLE
ImportError: cannot import name 'WuerstchenCombinedPipeline' from 'diffusers.pipelines.wuerstchen'

### ISSUE THREAD

**Issue by m4iccc** [tin2tin/Pallaidium#46]
The following error log from the python console, Blender 3.6.2, Trying to install Zeroscope XL, Stable Diffusion XL and Bark.
Filepath to an external drive, E:\PallaidiumBlender\

Ensuring: pip
Defaulting to user installation because normal site-packages is not writeable
Looking in links: c:\Users\Cinem\AppData\Local\Temp\tmp_phnydgk
Requirement already satisfied: setuptools in c:\program files\blender foundation\blender 3.6\3.6\python\lib\site-packages (63.2.0)
Requirement already satisfied: pip in c:\users\cinem\appdata\roaming\python\python310\site-packages (23.2.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\users\cinem\appdata\roaming\python\python310\site-packages (23.2.1)
Traceback (most recent call last):
  File "C:\Users\Cinem\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Pallaidium-main\__init__.py", line 867, in execute
    install_modules(self)
  File "C:\Users\Cinem\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Pallaidium-main\__init__.py", line 551, in install_modules
    import_module(self, "diffusers", "git+https://github.com/huggingface/diffusers.git")
  File "C:\Users\Cinem\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Pallaidium-main\__init__.py", line 450, in import_module
    exec("import " + module)
  File "<string>", line 1, in <module>
  File "C:\Users\Cinem\AppData\Roaming\Python\Python310\site-packages\diffusers\__init__.py", line 30, in <module>
    from .pipelines import OnnxRuntimeModel
  File "C:\Users\Cinem\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\__init__.py", line 19, in <module>
    from .auto_pipeline import AutoPipelineForImage2Image, AutoPipelineForInpainting, AutoPipelineForText2Image
  File "C:\Users\Cinem\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\auto_pipeline.py", line 55, in <module>
    from .wuerstchen import WuerstchenCombinedPipeline, WuerstchenDecoderPipeline
ImportError: cannot import name 'WuerstchenCombinedPipeline' from 'diffusers.pipelines.wuerstchen' (C:\Users\Cinem\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\__init__.py)
Error: Python: Traceback (most recent call last):
  File "C:\Users\Cinem\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Pallaidium-main\__init__.py", line 867, in execute
    install_modules(self)
  File "C:\Users\Cinem\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Pallaidium-main\__init__.py", line 551, in install_modules
    import_module(self, "diffusers", "git+https://github.com/huggingface/diffusers.git")
  File "C:\Users\Cinem\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Pallaidium-main\__init__.py", line 450, in import_module
    exec("import " + module)
  File "<string>", line 1, in <module>
  File "C:\Users\Cinem\AppData\Roaming\Python\Python310\site-packages\diffusers\__init__.py", line 30, in <module>
    from .pipelines import OnnxRuntimeModel
  File "C:\Users\Cinem\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\__init__.py", line 19, in <module>
    from .auto_pipeline import AutoPipelineForImage2Image, AutoPipelineForInpainting, AutoPipelineForText2Image
  File "C:\Users\Cinem\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\auto_pipeline.py", line 55, in <module>
    from .wuerstchen import WuerstchenCombinedPipeline, WuerstchenDecoderPipeline
ImportError: cannot import name 'WuerstchenCombinedPipeline' from 'diffusers.pipelines.wuerstchen' (C:\Users\Cinem\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\wuerstchen\__init__.py)

**Comment by tin2tin** [comment]
Looks like an error in the alpha version of the Diffusers module. 

Use this add-on to install the release version of Diffusers, by typing in "diffusers" and hit install.

Let me know if it works installing other places than the default path.

**Comment by tin2tin** [comment]
Looks like they have committed a fix for the wuerstchen errors: https://github.com/huggingface/diffusers/commits/main

So you need to uninstall diffusers(or all dependencies) and then run install dependencies again.

**Comment by tin2tin** [comment]
As Würstchen now has officially been implemented in Diffusers and also in Pallaidium, I'll close this.

If you want to try Würstchen, the Diffusers python module needs to be updated.
