### ISSUE TITLE
errors on Generate from Strips 

### ISSUE THREAD

**Issue by catafest** [tin2tin/Pallaidium#67]
Maybe my computer can't deal with the Python scripts or maybe is a bug ...
I used blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release
Generate movie prompt : 'Scene_rendered.mprendered, a beautiful women'
I added a camera, a monkey, and a light, I used the steps from [https://github.com/tin2tin/Pallaidium/issues/66](https://github.com/tin2tin/Pallaidium/issues/66)
These are the errors after downloading some files:
```
vae\diffusion_pytorch_model.fp16.safetensors not found
Downloading (…)e8e7b49d/config.json: 100%|████████████████████████████████████████████████████| 748/748 [00:00<?, ?B/s]
Downloading (…)rocessor_config.json: 100%|████████████████████████████████████████████████████| 342/342 [00:00<?, ?B/s]
Downloading (…)_checker/config.json: 100%|████████████████████████████████████████████████| 4.78k/4.78k [00:00<?, ?B/s]
Downloading (…)cheduler_config.json: 100%|████████████████████████████████████████████████████| 313/313 [00:00<?, ?B/s]
Downloading (…)cial_tokens_map.json: 100%|████████████████████████████████████████████| 472/472 [00:00<00:00, 46.9kB/s]
Downloading (…)_encoder/config.json: 100%|█████████████████████████████████████████████| 617/617 [00:00<00:00, 303kB/s]
Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████| 806/806 [00:00<?, ?B/s]
Downloading (…)tokenizer/merges.txt: 100%|██████████████████████████████████████████| 525k/525k [00:00<00:00, 1.27MB/s]
Downloading (…)b49d/vae/config.json: 100%|████████████████████████████████████████████████████| 552/552 [00:00<?, ?B/s]
Downloading (…)49d/unet/config.json: 100%|████████████████████████████████████████████████████| 748/748 [00:00<?, ?B/s]
Downloading (…)tokenizer/vocab.json: 100%|█████████████████████████████████████████| 1.06M/1.06M [00:03<00:00, 269kB/s]
Downloading (…)torch_model.fp16.bin: 100%|███████████████████████████████████████████| 167M/167M [10:30<00:00, 265kB/s]
Downloading pytorch_model.fp16.bin: 100%|████████████████████████████████████████████| 246M/246M [14:33<00:00, 282kB/s]
Fetching 16 files:  25%|███████████████▎                                             | 4/16 [45:48<2:17:25, 687.11s/it]
Traceback (most recent call last)::  79%|██████████████████████████████████▉         | 482M/608M [45:44<03:21, 626kB/s]
  File "C:\Users\catafest\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 2345, in executeh_model.fp16.bin:  14%|█████▌                                  | 241M/1.72G [14:27<1:09:01, 357kB/s]
    pipe = StableDiffusionInpaintPipeline.from_pretrained(                          | 482M/1.72G [45:43<38:28, 536kB/s]
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1041, in from_pretrained
    cached_folder = cls.download(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1742, in download
    cached_folder = snapshot_download(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\_snapshot_download.py", line 239, in snapshot_download
    thread_map(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\_snapshot_download.py", line 214, in _inner_hf_hub_download
    return hf_hub_download(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\file_download.py", line 1431, in hf_hub_download
    http_get(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\file_download.py", line 557, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 608103564 but has size 482356957 (pytorch_model.fp16.bin).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
Error: Python: Traceback (most recent call last):
  File "C:\Users\catafest\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 2345, in execute
    pipe = StableDiffusionInpaintPipeline.from_pretrained(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1041, in from_pretrained
    cached_folder = cls.download(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1742, in download
    cached_folder = snapshot_download(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\_snapshot_download.py", line 239, in snapshot_download
    thread_map(
Downloading pytorch_model.fp16.bin:  79%|██████████████████████████████████▉         | 482M/608M [45:44<11:55, 176kB/s]
Downloading (…)torch_model.fp16.bin:  28%|███████████▏                            | 482M/1.72G [45:43<1:57:16, 176kB/s]
Traceback (most recent call last):
  File "C:\Users\catafest\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 3285, in execute
    sequencer.generate_image()
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\catafest\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 2345, in execute
    pipe = StableDiffusionInpaintPipeline.from_pretrained(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1041, in from_pretrained
    cached_folder = cls.download(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1742, in download
    cached_folder = snapshot_download(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\_snapshot_download.py", line 239, in snapshot_download
    thread_map(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\_snapshot_download.py", line 214, in _inner_hf_hub_download
    return hf_hub_download(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\file_download.py", line 1431, in hf_hub_download
    http_get(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\file_download.py", line 557, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 608103564 but has size 482356957 (pytorch_model.fp16.bin).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
Location: C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\scripts\modules\bpy\ops.py:109

Error: Python: Traceback (most recent call last):
  File "C:\Users\catafest\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 3285, in execute
    sequencer.generate_image()
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\catafest\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 2345, in execute
    pipe = StableDiffusionInpaintPipeline.from_pretrained(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1041, in from_pretrained
    cached_folder = cls.download(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1742, in download
    cached_folder = snapshot_download(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\_snapshot_download.py", line 239, in snapshot_download
    thread_map(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\_snapshot_download.py", line 214, in _inner_hf_hub_download
    return hf_hub_download(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\file_download.py", line 1431, in hf_hub_download
    http_get(
  File "C:\Users\catafest\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\file_download.py", line 557, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 608103564 but has size 482356957 (pytorch_model.fp16.bin).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
Location: C:\blender-4.0.0-alpha+main.967d49dba48e-windows.amd64-release\4.0\scripts\modules\bpy\ops.py:109
```

**Comment by tin2tin** [comment]
Your download failed. Things to check: loads of free hdd space, internet connection. If both are okay, try again. 

You're downloading a model for Inpainting, that's the process where you use a mask to generate something new inside the masked area and not the img2img used when processing 3D Scene strips.

**Comment by tin2tin** [comment]
How is it going?

**Comment by tin2tin** [comment]
Please reopen if the problem persists.
