### ISSUE TITLE
error on 1.6 version when trying to use audio LDM 2 sound and bark 

### ISSUE THREAD

**Issue by vuaieo** [tin2tin/Pallaidium#79]
2023-11-13 04:07:57.420994: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-13 04:07:57.421025: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-13 04:07:57.421057: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-13 04:07:57.426374: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-13 04:07:58.076491: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Model:  cvssp/audioldm2
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████| 11/11 [00:01<00:00,  8.24it/s]
Generate: Audio/music (AudioLDM)
Seed: 945105
Prompt: running human
  0%|                                                                                                                      | 0/25 [00:00<?, ?it/s]/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:01<00:00, 20.89it/s]
Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.1/scripts/addons/Pallaidium-main/__init__.py", line 2423, in execute
    write_wav(filename, rate, audio.transpose())
UnboundLocalError: local variable 'write_wav' referenced before assignment
Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.1/scripts/addons/Pallaidium-main/__init__.py", line 2423, in execute
    write_wav(filename, rate, audio.transpose())
UnboundLocalError: local variable 'write_wav' referenced before assignment

 and this is for bark:
 
 Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.1/scripts/addons/Pallaidium-main/__init__.py", line 2272, in execute
    from bark.generation import (
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/api.py", line 5, in <module>
    from .generation import codec_decode, generate_coarse, generate_fine, generate_text_semantic
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/generation.py", line 6, in <module>
    from encodec import EncodecModel
  File "/home/vuaieo/.local/lib/python3.10/site-packages/encodec/__init__.py", line 12, in <module>
    from .model import EncodecModel
  File "/home/vuaieo/.local/lib/python3.10/site-packages/encodec/model.py", line 19, in <module>
    from .utils import _check_checksum, _linear_overlap_add, _get_checkpoint_url
  File "/home/vuaieo/.local/lib/python3.10/site-packages/encodec/utils.py", line 14, in <module>
    import torchaudio
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/_ops.py", line 852, in load_library
    ctypes.CDLL(path)
  File "/home/vuaieo/Desktop/UPBGE_4.1/4.1/python/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/vuaieo/.local/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at4_ops6conv1d4callERKNS_6TensorES4_RKN3c108optionalIS2_EENS5_8ArrayRefIlEESB_SB_l

now i suepr regret it ugrading,. how i can downlgrade to 1.5 again?

**Comment by tin2tin** [comment]
Let me know if this fixes your problem with write_wav?

I haven*t used AudioLDM and Bark much, so please share how you use it to get useful results in the Discussions > Cookbook
https://github.com/tin2tin/Pallaidium/discussions/categories/cookbook-share-your-genai-recipes-here

**Comment by vuaieo** [comment]
well thanks super much you really fixed it and now the audio ldm works again and bark thanks : )

but now i got another poblem which is that downloaded wuerstchen model and is still not enouth Vram memory. i thought the wuerstchen was specifically made for this reason. i even set to 512 pixels and is still too less.. on dream textures weven the SDXL model i can run 1024 but without refiner and with cpu offloading setting.

well i got so one another request that make a button to free up memory because changing model or featore what to generate dopesnt free up model and so need restart blender.

well thanks much for this super addon still cant wait for improvements : )
