### ISSUE TITLE
error when installing MusicGen Stereo model 

### ISSUE THREAD

**Issue by vuaieo** [tin2tin/Pallaidium#81]
hi i just wanetd update this super crazy good addon and try out the new music gen model you added today but i getting this error :

Model:  facebook/musicgen-stereo-small
Downloading (…)lve/main/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.75k/7.75k [00:00<00:00, 50.2MB/s]
Downloading model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.22G/1.22G [00:37<00:00, 32.2MB/s]
/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Downloading (…)neration_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 224/224 [00:00<00:00, 2.40MB/s]
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20.8k/20.8k [00:00<00:00, 70.4MB/s]
Downloading spiece.model: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 792k/792k [00:00<00:00, 3.33MB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.42M/2.42M [00:00<00:00, 7.24MB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.20k/2.20k [00:00<00:00, 19.7MB/s]
Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.1/scripts/addons/Pallaidium-main/__init__.py", line 2395, in execute
    music = pipe(prompt, forward_params={"max_new_tokens": min(audio_length_in_s*50, 1503)})
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/text_to_audio.py", line 138, in __call__
    return super().__call__(text_inputs, **forward_params)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1140, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1147, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1046, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/text_to_audio.py", line 112, in _forward
    output = self.model.generate(**model_inputs, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/models/musicgen/modeling_musicgen.py", line 2319, in generate
    input_ids, decoder_delay_pattern_mask = self.decoder.build_delay_pattern_mask(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/models/musicgen/modeling_musicgen.py", line 1077, in build_delay_pattern_mask
    torch.ones((bsz, num_codebooks, max_length), dtype=torch.long, device=input_ids.device) * -1
TypeError: ones(): argument 'size' failed to unpack the object at pos 3 with error "type must be tuple of ints,but got float"
Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/Desktop/UPBGE_4.1/4.1/python/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 924, in device_placement
    yield
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1046, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/text_to_audio.py", line 112, in _forward
    output = self.model.generate(**model_inputs, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/models/musicgen/modeling_musicgen.py", line 2319, in generate
    input_ids, decoder_delay_pattern_mask = self.decoder.build_delay_pattern_mask(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/models/musicgen/modeling_musicgen.py", line 1077, in build_delay_pattern_mask
    torch.ones((bsz, num_codebooks, max_length), dtype=torch.long, device=input_ids.device) * -1
TypeError: ones(): argument 'size' failed to unpack the object at pos 3 with error "type must be tuple of ints,but got float"

🖖

**Comment by tin2tin** [comment]
Dunno. Maybe the download failed and you need to retry?

**Comment by tin2tin** [comment]
Try updating the add-on. If it complains about a missing python module called soundfile, then click on Install Dependencies. 

... and let me know how it goes.

**Comment by vuaieo** [comment]
hi i just tryed to install dependencys and then run the musicgen model and got this :

Ensuring: pip
Looking in links: /tmp/tmpiiecl6kt
Requirement already satisfied: setuptools in ./UPBGE_4.1/4.1/python/lib/python3.10/site-packages (63.2.0)
Requirement already satisfied: pip in ./UPBGE_4.1/4.1/python/lib/python3.10/site-packages (23.3.1)
Requirement already satisfied: pip in ./UPBGE_4.1/4.1/python/lib/python3.10/site-packages (23.3.1)
/bin/sh: 1: sox: not found
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.
    
Requirement already satisfied: mediapipe in ./UPBGE_4.1/4.1/python/lib/python3.10/site-packages (0.10.8)
Requirement already satisfied: absl-py in /home/vuaieo/.local/lib/python3.10/site-packages (from mediapipe) (2.0.0)
Requirement already satisfied: attrs>=19.1.0 in /home/vuaieo/.local/lib/python3.10/site-packages (from mediapipe) (23.1.0)
Requirement already satisfied: flatbuffers>=2.0 in /home/vuaieo/.local/lib/python3.10/site-packages (from mediapipe) (23.5.26)
Requirement already satisfied: matplotlib in /home/vuaieo/.local/lib/python3.10/site-packages (from mediapipe) (3.7.2)
Requirement already satisfied: numpy in ./UPBGE_4.1/4.1/python/lib/python3.10/site-packages (from mediapipe) (1.26.2)
Requirement already satisfied: opencv-contrib-python in ./UPBGE_4.1/4.1/python/lib/python3.10/site-packages (from mediapipe) (4.8.1.78)
Requirement already satisfied: protobuf<4,>=3.11 in ./UPBGE_4.1/4.1/python/lib/python3.10/site-packages (from mediapipe) (3.20.3)
Requirement already satisfied: sounddevice>=0.4.4 in ./UPBGE_4.1/4.1/python/lib/python3.10/site-packages (from mediapipe) (0.4.6)
Requirement already satisfied: CFFI>=1.0 in /home/vuaieo/.local/lib/python3.10/site-packages (from sounddevice>=0.4.4->mediapipe) (1.15.1)
Requirement already satisfied: contourpy>=1.0.1 in /home/vuaieo/.local/lib/python3.10/site-packages (from matplotlib->mediapipe) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /home/vuaieo/.local/lib/python3.10/site-packages (from matplotlib->mediapipe) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/vuaieo/.local/lib/python3.10/site-packages (from matplotlib->mediapipe) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/vuaieo/.local/lib/python3.10/site-packages (from matplotlib->mediapipe) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /home/vuaieo/.local/lib/python3.10/site-packages (from matplotlib->mediapipe) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /home/vuaieo/.local/lib/python3.10/site-packages (from matplotlib->mediapipe) (10.0.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /home/vuaieo/.local/lib/python3.10/site-packages (from matplotlib->mediapipe) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/vuaieo/.local/lib/python3.10/site-packages (from matplotlib->mediapipe) (2.8.2)
Requirement already satisfied: pycparser in /home/vuaieo/.local/lib/python3.10/site-packages (from CFFI>=1.0->sounddevice>=0.4.4->mediapipe) (2.21)
Requirement already satisfied: six>=1.5 in /home/vuaieo/.local/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->mediapipe) (1.16.0)
Looking in indexes: https://download.pytorch.org/whl/cu118
Requirement already satisfied: xformers==0.0.22.post4 in /home/vuaieo/.local/lib/python3.10/site-packages (0.0.22.post4+cu118)
Requirement already satisfied: numpy in ./UPBGE_4.1/4.1/python/lib/python3.10/site-packages (from xformers==0.0.22.post4) (1.26.2)
Requirement already satisfied: torch==2.1.0 in /home/vuaieo/.local/lib/python3.10/site-packages (from xformers==0.0.22.post4) (2.1.0)
Requirement already satisfied: filelock in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (3.13.1)
Requirement already satisfied: typing-extensions in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (4.8.0)
Requirement already satisfied: sympy in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (1.12)
Requirement already satisfied: networkx in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (3.2.1)
Requirement already satisfied: jinja2 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (3.1.2)
Requirement already satisfied: fsspec in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (2023.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.18.1 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (2.18.1)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (12.1.105)
Requirement already satisfied: triton==2.1.0 in /home/vuaieo/.local/lib/python3.10/site-packages (from torch==2.1.0->xformers==0.0.22.post4) (2.1.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/vuaieo/.local/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.1.0->xformers==0.0.22.post4) (12.3.52)
Requirement already satisfied: MarkupSafe>=2.0 in /home/vuaieo/.local/lib/python3.10/site-packages (from jinja2->torch==2.1.0->xformers==0.0.22.post4) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /home/vuaieo/.local/lib/python3.10/site-packages (from sympy->torch==2.1.0->xformers==0.0.22.post4) (1.3.0)
Requirement already satisfied: numpy in ./UPBGE_4.1/4.1/python/lib/python3.10/site-packages (1.26.2)
Info: Installation of dependencies is finished.

Model:  facebook/musicgen-stereo-small
/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.1/scripts/addons/Pallaidium-main/__init__.py", line 2394, in execute
    music = pipe(prompt, forward_params={"max_new_tokens": int(min(audio_length_in_s*50, 1503))})
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/text_to_audio.py", line 138, in __call__
    return super().__call__(text_inputs, **forward_params)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1140, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1147, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1046, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/text_to_audio.py", line 112, in _forward
    output = self.model.generate(**model_inputs, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/models/musicgen/modeling_musicgen.py", line 2436, in generate
    output_values = self.audio_encoder.decode(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/models/encodec/modeling_encodec.py", line 737, in decode
    audio_values = self._decode_frame(audio_codes[0], audio_scales[0])
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/models/encodec/modeling_encodec.py", line 701, in _decode_frame
    embeddings = self.quantizer.decode(codes)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/models/encodec/modeling_encodec.py", line 434, in decode
    layer = self.layers[i]
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 293, in __getitem__
    return self._modules[self._get_abs_string_index(idx)]
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 283, in _get_abs_string_index
    raise IndexError(f'index {idx} is out of range')
IndexError: index 4 is out of range
Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/Desktop/UPBGE_4.1/4.1/python/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 924, in device_placement
    yield
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1046, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/text_to_audio.py", line 112, in _forward
    output = self.model.generate(**model_inputs, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/models/musicgen/modeling_musicgen.py", line 2436, in generate
    output_values = self.audio_encoder.decode(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/models/encodec/modeling_encodec.py", line 737, in decode
    audio_values = self._decode_frame(audio_codes[0], audio_scales[0])
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/models/encodec/modeling_encodec.py", line 701, in _decode_frame
    embeddings = self.quantizer.decode(codes)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/models/encodec/modeling_encodec.py", line 434, in decode
    layer = self.layers[i]
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 293, in __getitem__
    return self._modules[self._get_abs_string_index(idx)]
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 283, in _get_abs_string_index
    raise IndexError(f'index {idx} is out of range')
IndexError: index 4 is out of range

**Comment by tin2tin** [comment]
What is your os?

**Comment by vuaieo** [comment]
> What is your os?

Kubuntu 23.10 / Linux

**Comment by tin2tin** [comment]
Run this in the Blender text editor, and check the system console what it calls your system:
```
import platform
print(platform.system())
```

**Comment by vuaieo** [comment]
it prints 

![dmeZDOe](https://github.com/tin2tin/Pallaidium/assets/110411323/caafb7a6-fc5d-49e2-be9f-4cb3b9b663be)

**Comment by tin2tin** [comment]
I have no way to test the add-on on Linux, nor have I ever used Linux. Actually, I'm surprised that you're able to run the add-on at all. Anyway, now I've tried to do something about sox(which is not used on Windows). Pls, try it out and let me know if it works.

**Comment by vuaieo** [comment]
well looks like the addon is acting differently on 4.1 and 3.6.1 versions of blender.. 
this is what i get when trying to run musicgen model on 3.6.1:

Model:  facebook/musicgen-stereo-small
Traceback (most recent call last):
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1345, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 28, in <module>
    from ..image_processing_utils import BaseImageProcessor
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 28, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/image_transforms.py", line 47, in <module>
    import tensorflow as tf
  File "/home/vuaieo/.local/lib/python3.10/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/vuaieo/.local/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python.saved_model import saved_model
  File "/home/vuaieo/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/saved_model.py", line 20, in <module>
    from tensorflow.python.saved_model import builder
  File "/home/vuaieo/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/builder.py", line 23, in <module>
    from tensorflow.python.saved_model.builder_impl import _SavedModelBuilder
  File "/home/vuaieo/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/builder_impl.py", line 20, in <module>
    from google.protobuf.any_pb2 import Any
ModuleNotFoundError: No module named 'google.protobuf'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 2324, in execute
    from transformers import pipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1335, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1347, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
No module named 'google.protobuf'
Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1345, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 28, in <module>
    from ..image_processing_utils import BaseImageProcessor
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 28, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/image_transforms.py", line 47, in <module>
    import tensorflow as tf
  File "/home/vuaieo/.local/lib/python3.10/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/vuaieo/.local/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python.saved_model import saved_model
  File "/home/vuaieo/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/saved_model.py", line 20, in <module>
    from tensorflow.python.saved_model import builder
  File "/home/vuaieo/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/builder.py", line 23, in <module>
    from tensorflow.python.saved_model.builder_impl import _SavedModelBuilder
  File "/home/vuaieo/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/builder_impl.py", line 20, in <module>
    from google.protobuf.any_pb2 import Any
ModuleNotFoundError: No module named 'google.protobuf'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 2324, in execute
    from transformers import pipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1335, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1347, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
No module named 'google.protobuf'

**Comment by vuaieo** [comment]
oh well and now the audioLDM 2 models broke with with update XD but bark works

**Comment by tin2tin** [comment]
Properly, it's differences in the installed Python modules in the two versions of Blender. 

You can try to uninstall the dependencies, then check: `blender-4.0.0\blender-4.0.0-beta+v40.23e3f8f56396-windows.amd64-release\4.0\python\site-packages `if there are still folders called something with touch and delete them, restart Blender, install dependencies, and see if that improves anything. But trying to support Linux is pretty much mission impossible for me. And my only real hope is that someone comes along and is able to fix those things on Linux.

**Comment by vuaieo** [comment]
> Properly, it's differences in the installed Python modules in the two versions of Blender.
> 
> You can try to uninstall the dependencies, then check: `blender-4.0.0\blender-4.0.0-beta+v40.23e3f8f56396-windows.amd64-release\4.0\python\site-packages `if there are still folders called something with touch/sox etc. and delete them, restart Blender, install dependencies, and see if that improves anything. But trying to support Linux is pretty much mission impossible for me. And my only real hope is that someone comes along and is able to fix those things on Linux.

yeah right because on blender 4.1 the audioLDM2 still works but it broke opn 3.6.1

**Comment by vuaieo** [comment]
sorry i dont know where this path would be on linux  blender-4.0.0\blender-4.0.0-beta+v40.23e3f8f56396-windows.amd64-release\4.0\python\site-packages

well its ok lets stop then maybe better because we could do this whole days without you usign linux...
thanks much for this addon ill just use the last version withotu musicgen : )
i just hope maybe you would install linux since is really cool... seeyou 🖖

**Comment by tin2tin** [comment]
You can just search fro folders called: site-packages and see if they're located in a blender folder.

**Comment by vuaieo** [comment]
ok in this folder /home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/site-packages/

there isnt any touch/sox files but these:

![ZDVKAvp](https://github.com/tin2tin/Pallaidium/assets/110411323/8ad8727b-b9af-4883-a9e9-64e2e3f9c8c0)

**Comment by tin2tin** [comment]
Okay, there are more folders with that name on your computer, you can also check those. 
I have no idea why the latest update of my add-on doesn't install sox on your computer, but you can try to install it manually by using this add-on. Just type in sox and hit install: https://github.com/amb/blender_pip

Also, you might try Blender instead of the upbge fork, there might be differences between those.

**Comment by vuaieo** [comment]
ok tryed on 4.1 and 3.61 but same results still so i better really stiop this because asd long you dont install super nice linux OS then its maddness for you trying to figure out i think its way too much stress alreadyy i need stop thanks for all the help seetyou

wanted ask if you was thinking maybe on adding the shap e 3D generation iin your addon maybe?

![2023-11-14_01-03](https://github.com/tin2tin/Pallaidium/assets/110411323/0267c461-1f7f-4a89-b70d-06e76fa520b7)

**Comment by tin2tin** [comment]
For figuring out your 3.6.1 problem you'll need to google the error message and see if you can find a solution this way: "No module named 'google.protobuf'".

**Comment by tin2tin** [comment]
In the readme, I've made it a requirement to install on Windows, and thereby listed Linux as unsupported.
