### ISSUE TITLE
error on 1.7 version

### ISSUE THREAD

**Issue by vuaieo** [tin2tin/Pallaidium#84]
hi i tryed to update the addon from 1.6 to latest but now i get this error when installing dependencys:

Ensuring: pip
Looking in links: /tmp/tmpiwl2gs5f
Requirement already satisfied: setuptools in ./UPBGE41/4.1/python/lib/python3.10/site-packages (63.2.0)
Requirement already satisfied: pip in ./UPBGE41/4.1/python/lib/python3.10/site-packages (23.3.1)
Requirement already satisfied: pip in ./UPBGE41/4.1/python/lib/python3.10/site-packages (23.3.1)
Requirement already satisfied: transformers in ./UPBGE41/4.1/python/lib/python3.10/site-packages (4.35.2)
Requirement already satisfied: filelock in /home/vuaieo/.local/lib/python3.10/site-packages (from transformers) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /home/vuaieo/.local/lib/python3.10/site-packages (from transformers) (0.17.3)
Requirement already satisfied: numpy>=1.17 in ./UPBGE41/4.1/python/lib/python3.10/site-packages (from transformers) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /home/vuaieo/.local/lib/python3.10/site-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /home/vuaieo/.local/lib/python3.10/site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /home/vuaieo/.local/lib/python3.10/site-packages (from transformers) (2023.10.3)
Requirement already satisfied: requests in /home/vuaieo/.local/lib/python3.10/site-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /home/vuaieo/.local/lib/python3.10/site-packages (from transformers) (0.14.1)
Requirement already satisfied: safetensors>=0.3.1 in /home/vuaieo/.local/lib/python3.10/site-packages (from transformers) (0.4.0)
Requirement already satisfied: tqdm>=4.27 in /home/vuaieo/.local/lib/python3.10/site-packages (from transformers) (4.66.1)
Requirement already satisfied: fsspec in /home/vuaieo/.local/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (2023.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/vuaieo/.local/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (4.8.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./UPBGE41/4.1/python/lib/python3.10/site-packages (from requests->transformers) (2.0.10)
Requirement already satisfied: idna<4,>=2.5 in ./UPBGE41/4.1/python/lib/python3.10/site-packages (from requests->transformers) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./UPBGE41/4.1/python/lib/python3.10/site-packages (from requests->transformers) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in ./UPBGE41/4.1/python/lib/python3.10/site-packages (from requests->transformers) (2021.10.8)
Traceback (most recent call last):
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1345, in _get_module
  File "/home/vuaieo/Desktop/UPBGE41/4.1/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers.models'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.1/scripts/addons/Pallaidium-main/__init__.py", line 808, in execute
    install_modules(self)
  File "/home/vuaieo/.config/upbge/4.1/scripts/addons/Pallaidium-main/__init__.py", line 642, in install_modules
    import_module(self, "bark", "git+https://github.com/suno-ai/bark.git")
  File "/home/vuaieo/.config/upbge/4.1/scripts/addons/Pallaidium-main/__init__.py", line 535, in import_module
    exec("import " + module)
  File "<string>", line 1, in <module>
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/api.py", line 5, in <module>
    from .generation import codec_decode, generate_coarse, generate_fine, generate_text_semantic
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/generation.py", line 14, in <module>
    from transformers import BertTokenizer
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1335, in __getattr__
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1347, in _get_module
RuntimeError: Failed to import transformers.models.bert because of the following error (look up to see its traceback):
No module named 'transformers.models'
Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1345, in _get_module
  File "/home/vuaieo/Desktop/UPBGE41/4.1/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers.models'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.1/scripts/addons/Pallaidium-main/__init__.py", line 535, in import_module
    exec("import " + module)
  File "<string>", line 1, in <module>
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/api.py", line 5, in <module>
    from .generation import codec_decode, generate_coarse, generate_fine, generate_text_semantic
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/generation.py", line 14, in <module>
    from transformers import BertTokenizer
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1335, in __getattr__
  File "/home/vuaieo/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1347, in _get_module
RuntimeError: Failed to import transformers.models.bert because of the following error (look up to see its traceback):
No module named 'transformers.models'

why i always unlucky... i now broke the it completely because the audioldm2 doesnt work anymore too T___T

**Comment by tin2tin** [comment]
The latest version needs a new version of transformers. Try to uninstall all dependencies, close Blender, search for transformers on the hhd, delete folders if found, restart Blender, install dependencies.

**Comment by tin2tin** [comment]
Try this branch instead - I've tried to do some things about the installation process. Uninstall all dependencies first. Locate any bark folder on harddisk and delete it too, before installing this: https://github.com/tin2tin/Pallaidium/tree/Installation_fix

**Comment by tin2tin** [comment]
I've updated the main code with the changes from the fork. Let me know if it solves your problems, so I can close this report if it does.

**Comment by vuaieo** [comment]
❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥 hi so i installed the latest release on 3.6.1 and it gives me this error messege when i trying to click on install dependencys:

Ensuring: pip
Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 860, in execute
    install_modules(self)
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 614, in install_modules
    subprocess.call([pybin, "-m", "ensurepip"])
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/sys.prefix/bin/python'
Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 860, in execute
    install_modules(self)
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 614, in install_modules
    subprocess.call([pybin, "-m", "ensurepip"])
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/sys.prefix/bin/python'



❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥 and this messege when i click on deinstall dependencys:

Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 879, in execute
    uninstall_module_with_dependencies("torch")
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 839, in uninstall_module_with_dependencies
    dependencies = get_module_dependencies(module_name)
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 812, in get_module_dependencies
    result = subprocess.run(
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/sys.prefix/bin/python'
Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 879, in execute
    uninstall_module_with_dependencies("torch")
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 839, in uninstall_module_with_dependencies
    dependencies = get_module_dependencies(module_name)
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 812, in get_module_dependencies
    result = subprocess.run(
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vuaieo/Desktop/upbge-0.36.1-linux-x86_64/3.6/python/sys.prefix/bin/python'



❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥 and this error comes if i choosee musicgen model in the VSE:

/bin/sh: 1: sox: not found
2023-11-25 00:08:16,350  WARNING __init__.py 10 SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.
    
Model:  facebook/musicgen-stereo-small
/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Generate: MusicGen Stereo
Prompt: speaking of nonsence all day long
Seed: 446534
2023-11-25 00:08:59,934  WARNING file_info.py 305 This install of SoX cannot process .wav files.
Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 2524, in execute
    tfm.build_file(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/sox/transform.py", line 710, in build_file
    return self.build(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/sox/transform.py", line 609, in build
    args.extend(self._input_format_args(input_format))
  File "/home/vuaieo/.local/lib/python3.10/site-packages/sox/transform.py", line 193, in _input_format_args
    self._validate_input_format(input_format)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/sox/transform.py", line 159, in _validate_input_format
    raise ValueError(
ValueError: Invalid file_type. Must be one of []
Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/3.6/scripts/addons/Pallaidium-main/__init__.py", line 2524, in execute
    tfm.build_file(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/sox/transform.py", line 710, in build_file
    return self.build(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/sox/transform.py", line 609, in build
    args.extend(self._input_format_args(input_format))
  File "/home/vuaieo/.local/lib/python3.10/site-packages/sox/transform.py", line 193, in _input_format_args
    self._validate_input_format(input_format)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/sox/transform.py", line 159, in _validate_input_format
    raise ValueError(
ValueError: Invalid file_type. Must be one of []

❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥but the good is that audio LDM 2 and bark still works. so i searched for transformers and this i found but i not sure which one to delete , can you tell, because i really dont want to mess up other things.... 
![transformers](https://github.com/tin2tin/Pallaidium/assets/110411323/40c5764b-8a35-4535-9d8b-1e4bcdb2273c)

**Comment by tin2tin** [comment]
First try to manually install Sox.

**Comment by vuaieo** [comment]
and the super cool that the image captions works too now looks like so THANKS

**Comment by vuaieo** [comment]
i did try it just now through module addon like you showed me last time and its already installed it says but still same errors

**Comment by vuaieo** [comment]
well whatever at least got now suepr new feature of image captions thanks much ill wait then for next release : ) 🖖

**Comment by tin2tin** [comment]
I've completely removed sox, so try to redownload the add-on and install dependencies, and let me know how it goes. As you kno I'm not able to test on Linux...

**Comment by vuaieo** [comment]
hi, well i cant install or even uninstall dependencys since i get this error:

 Traceback (most recent call last):
  File "/home/vuaieo/.config/blender/3.6/scripts/addons/Pallaidium-main/__init__.py", line 881, in execute
    uninstall_module_with_dependencies("torch")
  File "/home/vuaieo/.config/blender/3.6/scripts/addons/Pallaidium-main/__init__.py", line 841, in uninstall_module_with_dependencies
    dependencies = get_module_dependencies(module_name)
  File "/home/vuaieo/.config/blender/3.6/scripts/addons/Pallaidium-main/__init__.py", line 814, in get_module_dependencies
    result = subprocess.run(
  File "/home/vuaieo/Desktop/blender-3.6.5-linux-x64/3.6/python/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/vuaieo/Desktop/blender-3.6.5-linux-x64/3.6/python/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/vuaieo/Desktop/blender-3.6.5-linux-x64/3.6/python/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vuaieo/Desktop/blender-3.6.5-linux-x64/3.6/python/sys.prefix/bin/python'
Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/.config/blender/3.6/scripts/addons/Pallaidium-main/__init__.py", line 881, in execute
    uninstall_module_with_dependencies("torch")
  File "/home/vuaieo/.config/blender/3.6/scripts/addons/Pallaidium-main/__init__.py", line 841, in uninstall_module_with_dependencies
    dependencies = get_module_dependencies(module_name)
  File "/home/vuaieo/.config/blender/3.6/scripts/addons/Pallaidium-main/__init__.py", line 814, in get_module_dependencies
    result = subprocess.run(
  File "/home/vuaieo/Desktop/blender-3.6.5-linux-x64/3.6/python/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/vuaieo/Desktop/blender-3.6.5-linux-x64/3.6/python/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/vuaieo/Desktop/blender-3.6.5-linux-x64/3.6/python/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vuaieo/Desktop/blender-3.6.5-linux-x64/3.6/python/sys.prefix/bin/python'

where are the dependencys saved even?

**Comment by tin2tin** [comment]
Normally it should just skip a module, if it can't find it, so I don't know why this happens. 

Maybe it's time for you to upgrade to the official Blender 4.0 release? 

And maybe search the entire harddisk for python module installation folders by searching for ex. torch, xformers, transformers. And if you find any, then clear out the entire folder(except if the is a python only installation, then you could just delete those specific folders).

**Comment by tin2tin** [comment]
@vuaieo Did you get it running? Can I close this report?

**Comment by vuaieo** [comment]
hi sry for late reply, i did download now 1.8 version today and wanted try before deleting tons of folders i found . and somehow ithe music gen started to work but it takes very long like 30 to 60 seconds to geneate, is this normal?

and the SDXL turbo works too but strange is that i can run it only first time and without refiner. the second time i click on generate it says i out of Vram  T___T
and so i tryed the stable diffusion turbo but i cvery disapointed because tis same fast like i tryed various models on drem texture addon. is that not normal? because i just today tryed the stable diffusion XL turbo on the official website and it runns crazy fast..

so if i installed the 1.8 verison it still says same error...
are you going to use linux finaly maybe? would be very cool sicne is very more fun than windows and would be too sad if this addon is only going to work erorrless on windows... and wanetd ask if you got discord channel or so so could much faster solve such issues than always waiting for reply here on github? well thanks anyway for super addon i think so there is no with music gen? i dont know but the speed really sucks conmpared to audio LDM2 generations... 🖖

**Comment by tin2tin** [comment]
Yes, MusicGen Stereo tekas some time. It is accessed through Transformers which doesn't have a time indicator like Diffusers lib has. 

I haven't tested SDXL turbo much. If there is a memory leak, well have to wait for the Diffusers folks to fix that.

Segmind /Dreamscape and Turbo seems equally fast on my 6 GB machine. May differ with more vram. 

I've already invested 9 months of work getting this to work on Windows, with constantly updating to the cutting edge models. This workload far too much. And adding the workload for supporting Linux would kill me. 

So, if you want to attract more Linux users to help to maintain it for Linux, please do, but I'm not going to add that to my uncompensated workload.  

As your problems seem to origin in previously installed incompatible python modules, I'm going to close this report. Thank you.
