### ISSUE TITLE
macOS development tester error result

### ISSUE THREAD

**Issue by enzyme69** [tin2tin/Pallaidium#90]
I am trying the macOS branch, hopefully to run this with proper CPU and transformers...

```
Prompt: impressionist painting IMG_4087, man and corgi portrait. loose brushwork, vibrant color, light and shadow play, captures feeling over form
Negative Prompt: anime, photorealistic, 35mm film, deformed, low contrast, noisy
Load: img2img/vid2img Model
Conversion Model:  stabilityai/sdxl-turbo
model_index.json: 100%|████████████████████████| 685/685 [00:00<00:00, 3.36MB/s]
text_encoder/config.json: 100%|████████████████| 565/565 [00:00<00:00, 5.77MB/s]
scheduler/scheduler_config.json: 100%|█████████| 459/459 [00:00<00:00, 4.10MB/s]
tokenizer/tokenizer_config.json: 100%|█████████| 704/704 [00:00<00:00, 3.70MB/s]
tokenizer/merges.txt: 100%|██████████████████| 525k/525k [00:00<00:00, 13.4MB/s]
tokenizer/special_tokens_map.json: 100%|███████| 586/586 [00:00<00:00, 9.14MB/s]
tokenizer/special_tokens_map.json:   0%|              | 0.00/586 [00:00<?, ?B/s]
tokenizer_2/special_tokens_map.json: 100%|█████████████████| 460/460 [00:00<00:00, 3.24MB/s]
tokenizer_2/tokenizer_config.json: 100%|███████████████████| 855/855 [00:00<00:00, 12.9MB/s]
text_encoder_2/config.json: 100%|██████████████████████████| 575/575 [00:00<00:00, 8.12MB/s]
unet/config.json: 100%|████████████████████████████████| 1.78k/1.78k [00:00<00:00, 23.6MB/s]
tokenizer/vocab.json: 100%|████████████████████████████| 1.06M/1.06M [00:00<00:00, 3.12MB/s]
vae/config.json: 100%|█████████████████████████████████████| 607/607 [00:00<00:00, 9.79MB/s]
tokenizer_2/vocab.json: 100%|██████████████████████████| 1.06M/1.06M [00:01<00:00, 1.02MB/s]
diffusion_pytorch_model.fp16.safetensors: 100%|██████████| 167M/167M [00:54<00:00, 3.04MB/s]
model.fp16.safetensors: 100%|██████████████████████████| 246M/246M [01:07<00:00, 3.66MB/s]s]
model.fp16.safetensors: 100%|███████████████████████| 1.39G/1.39G [03:43<00:00, 6.23MB/s]]s]
diffusion_pytorch_model.fp16.safetensors: 100%|████████| 5.14G/5.14G [08:26<00:00, 10.1MB/s]
Fetching 18 files: 100%|████████████████████████| 18/18 [08:28<00:00, 28.23s/it]2, 4.25MB/s]
The config attributes {'feature_extractor': [None, None], 'image_encoder': [None, None]} were passed to StableDiffusionXLImg2ImgPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.
Keyword arguments {'feature_extractor': [None, None], 'image_encoder': [None, None]} are not expected by StableDiffusionXLImg2ImgPipeline and will be ignored.
Loading pipeline components...:  14%|█████▌                                 | 1/7 [00:00<00:00,  6.29it/s]The config attributes {'attention_type': 'default', 'dropout': 0.0, 'reverse_transformer_layers_per_block': None} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...: 100%|███████████████████████████████████████| 7/7 [00:01<00:00,  6.35it/s]
Seed: 4087
Process: Image to Image
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 3636, in execute
    image = converter(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 859, in __call__
    ) = self.encode_prompt(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 332, in encode_prompt
    text_input_ids.to(device),
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 3636, in execute
    image = converter(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 859, in __call__
    ) = self.encode_prompt(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 332, in encode_prompt
    text_input_ids.to(device),
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA eTraceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 4120, in execute
    sequencer.generate_image()
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 3636, in execute
    image = converter(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 859, in __call__
    ) = self.encode_prompt(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 332, in encode_prompt
    text_input_ids.to(device),
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Location: /Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py:113

Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 4120, in execute
    sequencer.generate_image()
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 3636, in execute
    image = converter(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 859, in __call__
    ) = self.encode_prompt(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 332, in encode_prompt
    text_input_ids.to(device),
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Location: /Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py:113


```

**Comment by enzyme69** [comment]
In my case my Stripe is image ( I don't understand name and seed, how to setup properly), -- but  I believe it will be doing image 2 image, but I have zero generation so far.
```

1/1
Prompt: impressionist painting apple on table 123454, impressionist painting IMG_4087, impressionist painting IMG_4087, impressionist painting IMG_4087, man and corgi portrait. loose brushwork, vibrant color, light and shadow play, captures feeling over form. loose brushwork, vibrant color, light and shadow play, captures feeling over form. loose brushwork, vibrant color, light and shadow play, captures feeling over form. loose brushwork, vibrant color, light and shadow play, captures feeling over form
Negative Prompt: anime, photorealistic, 35mm film, deformed, low contrast, noisy
Load: img2img/vid2img Model
Conversion Model:  stabilityai/sdxl-turbo
The config attributes {'feature_extractor': [None, None], 'image_encoder': [None, None]} were passed to StableDiffusionXLImg2ImgPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.
Keyword arguments {'feature_extractor': [None, None], 'image_encoder': [None, None]} are not expected by StableDiffusionXLImg2ImgPipeline and will be ignored.
Loading pipeline components...:  29%|████████████████████████████████████▌                                                                                           | 2/7 [00:00<00:00, 10.21it/s]The config attributes {'attention_type': 'default', 'dropout': 0.0, 'reverse_transformer_layers_per_block': None} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  5.26it/s]
Seed: 123454
Process: Image to Image
Token indices sequence length is longer than the specified maximum sequence length for this model (132 > 77). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['captures feeling over form. loose brushwork, vibrant color, light and shadow play, captures feeling over form. loose brushwork, vibrant color, light and shadow play, captures feeling over form. loose brushwork, vibrant color, light and shadow play, captures feeling over form']
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 3636, in execute
    image = converter(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 859, in __call__
    ) = self.encode_prompt(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 332, in encode_prompt
    text_input_ids.to(device),
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 3636, in execute
    image = converter(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 859, in __call__
    ) = self.encode_prompt(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 332, in encode_prompt
    text_input_ids.to(device),
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA eTraceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 4120, in execute
    sequencer.generate_image()
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 3636, in execute
    image = converter(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 859, in __call__
    ) = self.encode_prompt(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 332, in encode_prompt
    text_input_ids.to(device),
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Location: /Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py:113

Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 4120, in execute
    sequencer.generate_image()
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 3636, in execute
    image = converter(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 859, in __call__
    ) = self.encode_prompt(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 332, in encode_prompt
    text_input_ids.to(device),
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Location: /Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py:113


```

**Comment by tin2tin** [comment]
Yeah, for some reason it still tries to insist on using CUDA. I tried something and updated the Mac branch. Try to redownload it. 

That error with sound file installation, I'll have to investigate. But lets first try to see if that CUDA problem is solvable.

**Comment by enzyme69** [comment]
maybe just turn off torch cuda thing?

sdxl turbo PINOKIO:

```
import gradio as gr
from diffusers import AutoPipelineForText2Image, AutoPipelineForImage2Image
from diffusers.utils import load_image
import torch

if torch.cuda.is_available():
  device = "cuda"
elif torch.backends.mps.is_available():
  device = "mps"
else:
  device = "cpu"


pipes = {
  "txt2img": AutoPipelineForText2Image.from_pretrained("stabilityai/sdxl-turbo", torch_dtype=torch.float16, variant="fp16").to(device),
  "img2img": AutoPipelineForImage2Image.from_pretrained("stabilityai/sdxl-turbo", torch_dtype=torch.float16, variant="fp16").to(device)
}

if device == "cpu":
  pipes["txt2img"].enable_model_cpu_offload()
  pipes["img2img"].enable_model_cpu_offload()


def run(prompt, image):
  print(f"prompt={prompt}, image={image}")
  if image is None:
    return pipes["txt2img"](prompt=prompt, num_inference_steps=1, guidance_scale=0.0).images[0]
  else:
    image = image.resize((512,512))
    print(f"img2img image={image}")
    return pipes["img2img"](prompt, image=image, num_inference_steps=3, strength=0.79, guidance_scale=0.1).images[0]

demo = gr.Interface(
    run,
    inputs=[
      gr.Textbox(label="Prompt"),
      gr.Image(type="pil")
    ],
    outputs=gr.Image(width=512,height=512),
    live=True
)
#demo.dependencies[0]["show_progress"] = "minimal"
demo.launch()

```

**Comment by enzyme69** [comment]
The idea is to have at least SDXL turbo to run. I am not a coder myself so I don't know what's missing. Yes on macOS it's all CPU, slower than NVIdia GPU, but not bad.

**Comment by tin2tin** [comment]
Did you check the latest version?

**Comment by enzyme69** [comment]
Latest version, new error: 

```
Info: Installing: bark module.
Info: Installing: diffusers module.
Info: Installing: tensorflow module.
Info: Installing: soundfile module.
Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 578, in import_module
    subprocess.call([python_exe, "import ", packageName])
NameError: name 'packageName' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/soundfile.py", line 267, in <module>
    _snd = _ffi.dlopen('sndfile')
  File "/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: ctypes.util.find_library() did not manage to locate a library called 'sndfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 866, in execute
    install_modules(self)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 710, in install_modules
    import_module(self, "soundfile", "PySoundFile")
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 607, in import_module
    exec("import " + module)
  File "<string>", line 1, in <module>
  File "/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/soundfile.py", line 276, in <module>
    _snd = _ffi.dlopen(_os.path.join(
  File "/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib'

2023-12-03 03:04:55.102 Blender[44352:2281090] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

```

**Comment by enzyme69** [comment]
Also:

```
Seed: 123454
Process: Image to Image
Token indices sequence length is longer than the specified maximum sequence length for this model (161 > 77). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['loose brushwork, vibrant color, light and shadow play, captures feeling over form. loose brushwork, vibrant color, light and shadow play, captures feeling over form. loose brushwork, vibrant color, light and shadow play, captures feeling over form. loose brushwork, vibrant color, light and shadow play, captures feeling over form. loose brushwork, vibrant color, light and shadow play, captures feeling over form']
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 3647, in execute
    image = converter(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 859, in __call__
    ) = self.encode_prompt(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 332, in encode_prompt
    text_input_ids.to(device),
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 3647, in execute
    image = converter(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 859, in __call__
    ) = self.encode_prompt(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 332, in encode_prompt
    text_input_ids.to(device),
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA eTraceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 4131, in execute
    sequencer.generate_image()
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 3647, in execute
    image = converter(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 859, in __call__
    ) = self.encode_prompt(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 332, in encode_prompt
    text_input_ids.to(device),
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Location: /Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py:113

Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 4131, in execute
    sequencer.generate_image()
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Pallaidium-Pallaidium_MacOS/__init__.py", line 3647, in execute
    image = converter(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 859, in __call__
    ) = self.encode_prompt(
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 332, in encode_prompt
    text_input_ids.to(device),
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Location: /Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py:113



```

**Comment by enzyme69** [comment]
Maybe Dream Texture addon install can show the way:
https://github.com/carson-katri/dream-textures

**Comment by tin2tin** [comment]
Question is if something special needs to be done on a Mac to install torch.

**Comment by enzyme69** [comment]
Also this:
https://github.com/radames/Real-Time-Latent-Consistency-Model/issues/15

**Comment by enzyme69** [comment]
Could this also help? 
https://g.co/bard/share/f8b1565bb26e

**Comment by tin2tin** [comment]
If you potentially have a lot of old python modules installed, try Uninstall Dependencies. Restart Blender Install Dependencies. If it is using cached versions, search the closed issues here for torch and there is a big thread on how to manually remove python modules completely.

**Comment by enzyme69** [comment]
I don't quite mess with that, but usually this is done from the addon install requirements? 

Anyhow, I think the module isn't properly installed, but I know Dream Texture works on macOS, but slightly slow. 

A better way is if Palladium connect to ComfyUI -- as server backend. I have ComfyUI working and fast.

**Comment by enzyme69** [comment]
Python Module Manager list: 
<img width="539" alt="Screenshot 2023-12-07 at 11 25 00 am" src="https://github.com/tin2tin/Pallaidium/assets/3952687/53b963dc-1c53-4fc3-bdf8-539a72b73361">
<img width="403" alt="Screenshot 2023-12-07 at 11 25 11 am" src="https://github.com/tin2tin/Pallaidium/assets/3952687/aaf23167-e3d0-478a-a666-56591aedf98b">
<img width="440" alt="Screenshot 2023-12-07 at 11 25 06 am" src="https://github.com/tin2tin/Pallaidium/assets/3952687/ff062b61-7efb-4044-b41a-e19e45fc33db">

---
btw:
Apple just release "mlx" and probably can install stable diffusion this way via its mlx module?
https://github.com/ml-explore/mlx


Alternatively, I still think the ComfyUI backend is worth testing on your side:
1. ComfyUI server running and can generate (also with custom workflow)
2. Pallaidium could pull images from generated AI.
3. Simpler?

**Comment by enzyme69** [comment]
In your script, can you just "turn off CUDA" because macOS stable diffusion uses something else.

**Comment by tin2tin** [comment]
We tried a few things, and apparently they do not solve the problems, so, I'm sorry, there is no way I can try to solve the Mac problems without having a Mac, and for that reason I'll have to close this report as it is unsupported.
