### ISSUE TITLE
ModuleNotFoundError: No module named 'google.protobuf

### ISSUE THREAD

**Issue by gerroon** [tin2tin/Pallaidium#94]
I am getting this error :( I did install the dependencies.

![image](https://github.com/tin2tin/Pallaidium/assets/8519469/5024d741-b173-49ee-8487-5a2d729f8d03)

```

RuntimeError: Failed to import transformers.image_processing_utils because of the following error (look up to see its traceback):
No module named 'google.protobuf'
Location: C:\BLENDER\4.1\scripts\modules\bpy\ops.py:109

Error: Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Pallaidium\__init__.py", line 4302, in execute
    sequencer.generate_image()
  File "C:\BLENDER\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\BLENDER\4.1\python\lib\site-packages\transformers\utils\import_utils.py", line 1353, in _get_module
    self._name = name
  File "C:\BLENDER\4.1\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\BLENDER\4.1\python\lib\site-packages\transformers\image_processing_utils.py", line 28, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "C:\BLENDER\4.1\python\lib\site-packages\transformers\image_transforms.py", line 47, in <module>
    import tensorflow as tf
  File "C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\tensorflow\__init__.py", line 48, in <module>
    from tensorflow._api.v2 import __internal__
  File "C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\tensorflow\_api\v2\__internal__\autograph\__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
  File "C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\autograph\core\ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\autograph\utils\__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\autograph\utils\context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\framework\ops.py", line 29, in <module>
    from tensorflow.core.framework import attr_value_pb2
  File "C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ModuleNotFoundError: No module named 'google.protobuf'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\BLENDER\4.1\python\lib\site-packages\transformers\utils\import_utils.py", line 1355, in _get_module

RuntimeError: Failed to import transformers.image_processing_utils because of the following error (look up to see its traceback):
No module named 'google.protobuf'
Location: C:\BLENDER\4.1\scripts\modules\bpy\ops.py:109

```

**Comment by tin2tin** [comment]
I can see I have protobuf 4.32.4 installed. It is not a module which is directly installed by Pallaidium, but it may be a module installed by one of the modules Pallaidium is using. Maybe first try to:

- Restart Blender
- hit Install Dependencies(as sometimes things fail first time(for unknown reasons)). 
- Restart Blender. 

And if that doesn't solve it, then use this add-on to install it manually: https://github.com/amb/blender_pip
- Type in "protobuf" and hit install. 
- Hit List to check if it is installed. 

Let me know if this solves your problem, so I can add it to the install procedure.

**Comment by gerroon** [comment]
Thanks for the help. Installing protobuf manually resolved the issue.

**Comment by tin2tin** [comment]
Thank you!
