### ISSUE TITLE
Bug - cant find python linux

### ISSUE THREAD

**Issue by statixVFX** [tin2tin/Pallaidium#99]
It looks for the binary "python" but as of blender 4.1 on linux at least the binary is called python3.11

If I symlink it to "python" it works. 

`Pallaidium dependencies needs to be installed and then Blender needs to be restarted.
Ensuring: pip
Traceback (most recent call last):
  File "/root/.config/blender/4.1/scripts/addons/Pallaidium-main/__init__.py", line 905, in execute
    install_modules(self)
  File "/root/.config/blender/4.1/scripts/addons/Pallaidium-main/__init__.py", line 657, in install_modules
    subprocess.call([pybin, "-m", "ensurepip"])
  File "/opt/blender/4.1/python/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/blender/4.1/python/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/blender/4.1/python/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/blender/4.1/python/bin/python'
Error: Python: Traceback (most recent call last):
  File "/root/.config/blender/4.1/scripts/addons/Pallaidium-main/__init__.py", line 657, in install_modules
    subprocess.call([pybin, "-m", "ensurepip"])
  File "/opt/blender/4.1/python/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/blender/4.1/python/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/blender/4.1/python/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/blender/4.1/python/bin/python'

`

**Comment by tin2tin** [comment]
Thanks. I haven't tested Pallaidium on 4.1 yet. 

It looks like it is Python 3.11 for Blender 4.1:
https://projects.blender.org/blender/blender/issues/113157

Uh, I hope this Python update will not break any of the dependencies.

**Comment by tin2tin** [comment]
@statixVFX 4.1 seems to run fine on Windows 11. I'm not on Linux, and can't do support on that platform. It is possible for you to submit a patch which fixes this problem for you and other Linux users?

**Comment by tin2tin** [comment]
No reply for a month, makes me think that this has been solved. If not, please reopen.

**Comment by jmanhype** [comment]
still broken im on linux

**Comment by tin2tin** [comment]
What does broken mean? For Linux issues, please add them in the open Linux thread, so a potential Linux dev will be able to find it.
